### PR TITLE
fix: add missing status type

### PR DESCRIPTION
**Pull request by casperiv0**
This PR includes::

- Add missing `status` field for getting the payment methods.

### CODE REVIEW

**Comment by janpaepke** [comment]
Hi @casperiv0, I would suggest this to be an enum, similar to `PaymentStatus` or `OrderStatus`.
Would you mind updating the pr?

**Comment by casperiv0** [comment]
@janpaepke done!

**Comment by janpaepke** [comment]
lgtm

@fjbender @Pimm we should merge this before doing the major release.

**Review by edorivai — APPROVED** [review]
LGTM

**Comment by casperiv0** [comment]
Sure! I'm be able to update to the newer version once it's out. Though, to confirm, you simply mean here: rebase my PR from the `master`/`main` branch, right?

**Pull request merged**
